stages:
  train_val_split:
    cmd: python challenges/train_val_split.py
    deps:
    - challenges/train_val_split.py
    - data/raw/train
    params:
    - data_dir_train
    - seed
    - train_val_split
    outs:
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
  featurize:
    cmd: python challenges/onset-detection/extract_features.py
    deps:
    - challenges/onset-detection/extract_features.py
    - data/raw/test
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
    params:
    - data_dir_test
    - featurize
    outs:
    - data/interim/
  prepare_labels:
    cmd: python challenges/onset-detection/prepare_labels.py
    deps:
    - challenges/onset-detection/prepare_labels.py
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
    params:
    - featurize.fps
    outs:
    - data/processed/train/labels/
    - data/processed/val/labels/
  combine_features:
    cmd: python challenges/onset-detection/combine_features_to_dataframe.py
    deps:
    - challenges/onset-detection/combine_features_to_dataframe.py
    - data/interim/
    - data/processed/train/labels
    - data/processed/val/labels
    params:
    - featurize.fps
    outs:
    - data/processed/train/data.csv
    - data/processed/val/data.csv
    - data/processed/test/data.csv
