#challenge-wide global settings
seed: 42
train_val_split: 0.8
data_dir_train: data/raw/train   # directory containing the .wav files for training
data_dir_test: data/raw/test   # directory containing the .wav files for testing

featurize:
  fps: 14.0
  frame_size: 3150
  ewm_spans:
  - 3
  - 6

train:
  batch_size: 128
  epochs: 64
  learning_rate: 0.003
  weight_decay: 0.0003
  model_file_name: fastai-tabular
  layers: [256, 128, 128]
  dropout_probs: [0.05, 0.1, 0.15]
