#challenge-wide global settings
seed: 42
train_val_split: 0.8
data_dir_train: "data/raw/train" # directory containing the .wav files for training
data_dir_test: "data/raw/test" # directory containing the .wav files for testing

featurize:
  fps: 20.0
  frame_size: 4410

train:
  batch_size: 64
  epochs: 42
  learning_rate: 0.001
  model_file_name: "fastai-tabular"