vars:
  - ../../params.yaml

stages:
  train_val_split:
    wdir: ../../
    cmd: python challenges/train_val_split.py
    deps:
    - challenges/train_val_split.py
    - data/raw/train
    params:
    - data_dir_train
    - seed
    - train_val_split
    outs:
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
  featurize:
    wdir: ../../
    cmd: python challenges/onset-detection/extract_features.py
    deps:
    - challenges/onset-detection/extract_features.py
    - data/raw/test
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
    params:
    - data_dir_test
    - onset_detection.featurize
    outs:
    - data/interim/onset-detection/
  prepare_labels:
    wdir: ../../
    cmd: python challenges/onset-detection/prepare_labels.py
    deps:
    - challenges/onset-detection/prepare_labels.py
    - data/processed/train_files.pkl
    - data/processed/val_files.pkl
    params:
    - onset_detection.featurize.fps
    outs:
    - data/processed/onset-detection/train/labels/
    - data/processed/onset-detection/val/labels/
  combine_features:
    wdir: ../../
    cmd: python challenges/onset-detection/combine_features_to_dataframe.py
    deps:
    - challenges/onset-detection/combine_features_to_dataframe.py
    - data/interim/onset-detection/
    - data/processed/onset-detection/train/labels
    - data/processed/onset-detection/val/labels
    params:
    - onset_detection.featurize.fps
    - onset_detection.featurize.frame_size
    outs:
    - data/processed/onset-detection/train/data.csv
    - data/processed/onset-detection/val/data.csv
    - data/processed/onset-detection/test/data.csv
  train:
    wdir: ../../
    cmd: python challenges/onset-detection/train.py
    deps:
    - challenges/onset-detection/train.py
    - data/processed/onset-detection/train/data.csv
    - data/processed/onset-detection/val/data.csv
    params:
    - seed
    - onset_detection.train
    outs:
    - models/${onset_detection.train.model_file_name}.pth
    metrics:
    - reports/onset-detection/dvclive.json:
        cache: false
    plots:
    - reports/onset-detection/dvclive/scalars:
        cache: false
  predict:
    wdir: ../../
    cmd: python challenges/onset-detection/test.py
    deps:
    - challenges/onset-detection/test.py
    - data/processed/onset-detection/train/data.csv
    - data/processed/onset-detection/val/data.csv
    - data/processed/onset-detection/test/data.csv
    - models/${onset_detection.train.model_file_name}.pth
    params:
    - seed
    - onset_detection.train.batch_size
    - onset_detection.train.model_file_name
    outs:
    - reports/onset-detection/test-df.csv
    - reports/onset-detection/test-onsets.json:
        cache: false
    - reports/onset-detection/val-onsets.json
    - reports/onset-detection/val-targets.json
    plots:
    - reports/onset-detection/val-df.csv:
        cache: false
        template: confusion
        x: onset
        y: "onset prediction"
  evaluate:
    wdir: ../../
    cmd: python challenges/onset-detection/eval_onsets.py --submission reports/onset-detection/val-onsets.json --target reports/onset-detection/val-targets.json
    deps:
    - challenges/onset-detection/eval_onsets.py
    - reports/onset-detection/val-onsets.json
    - reports/onset-detection/val-targets.json
    metrics:
    - reports/onset-detection/metrics.json:
        cache: false